f1:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: ../f1.duckdb
      schema: gold
      threads: 1
    ci:
      type: duckdb
      path: ../f1_fixtures.duckdb
      schema: gold
      threads: 1
